// e.g. rolld(4) rolls a d4
export function rolld(dieNumber) {
  return Math.floor(Math.random() * (dieNumber - 1 + 1) + 1);
}

export const treasureTable = [
  {
    type: 1,
    pctToHaveGold: 0.5,
    numGold: { numDice: 2, dieNum: 4, multiplier: 10 },
    pctToHaveGems: 0.1,
    numGems: { dieNum: 4, adjustment: 0 },
    gemValueAdjustment: -10,
    pctToHaveExtItem: 0.1,
    numExtItems: { dieNum: 2, adjustment: 0 },
    pctToHaveMagicItems: 0.05,
    numMagicItems: 1,
    maxXPValueForMagicItem: 100
  },
  {
    type: 2,
    pctToHaveGold: 0.55,
    numGold: { numDice: 4, dieNum: 4, multiplier: 10 },
    pctToHaveGems: 0.2,
    numGems: { dieNum: 4, adjustment: 1 },
    gemValueAdjustment: -8,
    pctToHaveExtItem: 0.2,
    numExtItems: { dieNum: 2, adjustment: 1 },
    pctToHaveMagicItems: 0.1,
    numMagicItems: 1,
    maxXPValueForMagicItem: 200
  },
  {
    type: 3,
    pctToHaveGold: 0.6,
    numGold: { numDice: 6, dieNum: 4, multiplier: 10 },
    pctToHaveGems: 0.3,
    numGems: { dieNum: 4, adjustment: 2 },
    gemValueAdjustment: -6,
    pctToHaveExtItem: 0.3,
    numExtItems: { dieNum: 2, adjustment: 2 },
    pctToHaveMagicItems: 0.15,
    numMagicItems: 1,
    maxXPValueForMagicItem: 300
  },
  {
    type: 4,
    pctToHaveGold: 0.65,
    numGold: { numDice: 8, dieNum: 4, multiplier: 10 },
    pctToHaveGems: 0.4,
    numGems: { dieNum: 4, adjustment: 3 },
    gemValueAdjustment: -4,
    pctToHaveExtItem: 0.4,
    numExtItems: { dieNum: 2, adjustment: 3 },
    pctToHaveMagicItems: 0.2,
    numMagicItems: 1,
    maxXPValueForMagicItem: 500
  },
  {
    type: 5,
    pctToHaveGold: 0.7,
    numGold: { numDice: 2, dieNum: 6, multiplier: 50 },
    pctToHaveGems: 0.5,
    numGems: { dieNum: 6, adjustment: 2 },
    gemValueAdjustment: -2,
    pctToHaveExtItem: 0.5,
    numExtItems: { dieNum: 4, adjustment: 2 },
    pctToHaveMagicItems: 0.3,
    numMagicItems: { dieNum: 2 },
    maxXPValueForMagicItem: 800
  },
  {
    type: 6,
    pctToHaveGold: 0.75,
    numGold: { numDice: 4, dieNum: 6, multiplier: 50 },
    pctToHaveGems: 0.6,
    numGems: { dieNum: 6, adjustment: 3 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.6,
    numExtItems: { dieNum: 4, adjustment: 3 },
    pctToHaveMagicItems: 0.4,
    numMagicItems: { dieNum: 2 },
    maxXPValueForMagicItem: 1300
  },
  {
    type: 7,
    pctToHaveGold: 0.8,
    numGold: { numDice: 6, dieNum: 6, multiplier: 50 },
    pctToHaveGems: 0.7,
    numGems: { dieNum: 6, adjustment: 4 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.7,
    numExtItems: { dieNum: 4, adjustment: 4 },
    pctToHaveMagicItems: 0.5,
    numMagicItems: { dieNum: 2 },
    maxXPValueForMagicItem: 2100
  },
  {
    type: 8,
    pctToHaveGold: 0.85,
    numGold: { numDice: 8, dieNum: 6, multiplier: 50 },
    pctToHaveGems: 0.8,
    numGems: { dieNum: 6, adjustment: 5 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.8,
    numExtItems: { dieNum: 4, adjustment: 5 },
    pctToHaveMagicItems: 0.6,
    numMagicItems: { dieNum: 2 },
    maxXPValueForMagicItem: 3400
  },
  {
    type: 9,
    pctToHaveGold: 0.9,
    numGold: { numDice: 2, dieNum: 8, multiplier: 100 },
    pctToHaveGems: 0.9,
    numGems: { dieNum: 8, adjustment: 4 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.9,
    numExtItems: { dieNum: 6, adjustment: 4 },
    pctToHaveMagicItems: 0.7,
    numMagicItems: { dieNum: 3 },
    maxXPValueForMagicItem: 5500
  },
  {
    type: 10,
    pctToHaveGold: 0.91,
    numGold: { numDice: 4, dieNum: 8, multiplier: 100 },
    pctToHaveGems: 0.91,
    numGems: { dieNum: 8, adjustment: 4 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.91,
    numExtItems: { dieNum: 6, adjustment: 5 },
    pctToHaveMagicItems: 0.8,
    numMagicItems: { dieNum: 3 }
  },
  {
    type: 11,
    pctToHaveGold: 0.92,
    numGold: { numDice: 6, dieNum: 8, multiplier: 100 },
    pctToHaveGems: 0.92,
    numGems: { dieNum: 8, adjustment: 6 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.92,
    numExtItems: { dieNum: 6, adjustment: 6 },
    pctToHaveMagicItems: 0.9,
    numMagicItems: { dieNum: 3 }
  },
  {
    type: 12,
    pctToHaveGold: 0.93,
    numGold: { numDice: 8, dieNum: 8, multiplier: 100 },
    pctToHaveGems: 0.93,
    numGems: { dieNum: 8, adjustment: 7 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.93,
    numExtItems: { dieNum: 6, adjustment: 7 },
    pctToHaveMagicItems: 0.92,
    numMagicItems: { dieNum: 3 }
  },
  {
    type: 13,
    pctToHaveGold: 0.94,
    numGold: { numDice: 2, dieNum: 10, multiplier: 200 },
    pctToHaveGems: 0.94,
    numGems: { dieNum: 10, adjustment: 6 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.94,
    numExtItems: { dieNum: 8, adjustment: 6 },
    pctToHaveMagicItems: 0.94,
    numMagicItems: { dieNum: 4 }
  },
  {
    type: 14,
    pctToHaveGold: 0.95,
    numGold: { numDice: 4, dieNum: 10, multiplier: 200 },
    pctToHaveGems: 0.95,
    numGems: { dieNum: 10, adjustment: 7 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.95,
    numExtItems: { dieNum: 8, adjustment: 7 },
    pctToHaveMagicItems: 0.96,
    numMagicItems: { dieNum: 4 }
  },
  {
    type: 15,
    pctToHaveGold: 0.96,
    numGold: { numDice: 6, dieNum: 10, multiplier: 200 },
    pctToHaveGems: 0.96,
    numGems: { dieNum: 10, adjustment: 8 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.96,
    numExtItems: { dieNum: 8, adjustment: 8 },
    pctToHaveMagicItems: 0.98,
    numMagicItems: { dieNum: 4 }
  },
  {
    type: 16,
    pctToHaveGold: 0.97,
    numGold: { numDice: 8, dieNum: 10, multiplier: 200 },
    pctToHaveGems: 0.97,
    numGems: { dieNum: 10, adjustment: 9 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.97,
    numExtItems: { dieNum: 8, adjustment: 9 },
    pctToHaveMagicItems: 0.99,
    numMagicItems: { dieNum: 4 }
  },
  {
    type: 17,
    pctToHaveGold: 0.98,
    numGold: { numDice: 2, dieNum: 12, multiplier: 400 },
    pctToHaveGems: 0.98,
    numGems: { dieNum: 12, adjustment: 8 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.98,
    numExtItems: { dieNum: 8, adjustment: 8 },
    pctToHaveMagicItems: 1,
    numMagicItems: { dieNum: 6 }
  },
  {
    type: 18,
    pctToHaveGold: 0.99,
    numGold: { numDice: 4, dieNum: 12, multiplier: 400 },
    pctToHaveGems: 0.99,
    numGems: { dieNum: 12, adjustment: 9 },
    gemValueAdjustment: 0,
    pctToHaveExtItem: 0.99,
    numExtItems: { dieNum: 8, adjustment: 9 },
    pctToHaveMagicItems: 1,
    numMagicItems: { dieNum: 6 }
  }
];