import { Chance } from "chance";
const chance = new Chance();

export const magicItemsIndex = 100;

const getMinMaxItem = (magicTypeTable) => {
  const roll = chance.integer({ min: 0, max: magicTypeTable.length - 1 });
  return magicTypeTable[roll];
};

export const getMagicItem = (maxXP) => {
  // filter magicItemsTable based on maxXP for this treasure level
  const filteredMagicItems = filterMagicItems(maxXP);

  // select randomly via array indices
  const roll = chance.integer({ min: 0, max: filteredMagicItems.length - 1 });
  const magicType = filteredMagicItems[roll];
  const itemType = getMinMaxItem(magicType.options);

  let item;
  if (itemType.options) {
    const midItem = getMinMaxItem(itemType.options);
    let generatedItem;
    if (midItem.options) {
      if (typeof midItem.options[0] === "string") {
        generatedItem =
          midItem.options[
          chance.integer({ min: 0, max: midItem.options.length - 1 })
          ];
      } else {
        generatedItem = getMinMaxItem(midItem.options).name;
      }
      item = { ...midItem, name: generatedItem };
    } else {
      item = midItem;
    }
  } else {
    item = { ...itemType, type: magicType.name };
  }

  if (magicType.bonuses) {
    const bonus = getMinMaxItem(magicType.bonuses);

    if (!item.value) {
      item.value = bonus.value;
    }

    if (!item.exp) {
      item.exp = bonus.exp;
    }

    item.type = bonus.type;
  }

  return item;
};

const filterMagicItems = (maxXP) => {
  if (!maxXP) {
    maxXP = 100000; // default maxXP to a crazy high number if not provided
  }
  let filteredList = [];
  for (const magicItemType of magicItemsTable) {
    if (magicItemType.bonuses) {
      let filteredItemType = {
        ...magicItemType,
        bonuses: magicItemType.bonuses.filter((bonus) => bonus.exp <= maxXP),
      };
      if (filteredItemType.bonuses.length > 0) {
        filteredList.push(filteredItemType);
      }
    } else if (magicItemType.options) {
      let filteredItemType = {
        ...magicItemType,
        options: magicItemType.options.filter((option) => option.exp <= maxXP),
      };
      if (filteredItemType.options.length > 0) {
        filteredList.push(filteredItemType);
      }
    }
  }
  return filteredList;
};

export const magicItemsTable = [
  {
    percentile: "1-15%",
    name: "Potion",
    min: 1,
    max: 15,
    options: [
      {
        name: "Aid",
        value: 400,
        exp: 200,
        min: 1,
        max: 3,
      },
      {
        name: "Bless (oil)",
        value: 300,
        exp: 100,
        min: 4,
        max: 6,
      },
      {
        name: "Blur",
        value: 400,
        exp: 200,
        min: 7,
        max: 9,
      },
      {
        name: "Clairaudience/Clairvoyance",
        value: 500,
        exp: 300,
        min: 10,
        max: 12,
      },
      {
        name: "Delay Toxin",
        value: 400,
        exp: 200,
        min: 13,
        max: 15,
      },
      {
        name: "Endure Heat/Cold",
        value: 300,
        exp: 100,
        min: 16,
        max: 18,
      },
      {
        name: "Fly",
        value: 500,
        exp: 300,
        min: 19,
        max: 21,
      },
      {
        name: "Gas Form",
        value: 500,
        exp: 300,
        min: 22,
        max: 24,
      },
      {
        name: "Giant Strength",
        value: 700,
        exp: 500,
        min: 25,
        max: 27,
      },
      {
        name: "Haste",
        value: 500,
        exp: 300,
        min: 28,
        max: 30,
      },
      {
        name: "Heal",
        value: 800,
        exp: 600,
        min: 31,
        max: 33,
      },
      {
        name: "Heal Critical Wounds",
        value: 500,
        exp: 300,
        min: 34,
        max: 36,
      },
      {
        name: "Heal Light Wound",
        value: 300,
        exp: 100,
        min: 37,
        max: 39,
      },
      {
        name: "Heal Serious Wounds",
        value: 700,
        exp: 500,
        min: 40,
        max: 42,
      },
      {
        name: "Invisibility (potion or oil)",
        value: 400,
        exp: 200,
        min: 43,
        max: 45,
      },
      {
        name: "Levitation (potion or oil)",
        value: 400,
        exp: 200,
        min: 46,
        max: 48,
      },
      {
        name: "Neutralize Toxin",
        value: 600,
        exp: 400,
        min: 49,
        max: 51,
      },
      {
        name: "Nondetection",
        value: 500,
        exp: 300,
        min: 52,
        max: 54,
      },
      {
        name: "Pass with Woodland Stride",
        value: 300,
        exp: 100,
        min: 55,
        max: 57,
      },
      {
        name: "Protection from Disposition",
        value: 300,
        exp: 100,
        min: 58,
        max: 60,
      },
      {
        name: "Protection from Normal Missiles",
        value: 500,
        exp: 300,
        min: 61,
        max: 63,
      },
      {
        name: "Remove Bane",
        value: 500,
        exp: 300,
        min: 64,
        max: 66,
      },
      {
        name: "Remove Malady",
        value: 500,
        exp: 300,
        min: 67,
        max: 69,
      },
      {
        name: "Restoration",
        value: 700,
        exp: 400,
        min: 70,
        max: 72,
      },
      {
        name: "Restore Movement",
        value: 400,
        exp: 200,
        min: 73,
        max: 75,
      },
      {
        name: "Restore Sight and Hearing",
        value: 500,
        exp: 300,
        min: 76,
        max: 78,
      },
      {
        name: "Sanctuary",
        value: 300,
        exp: 100,
        min: 79,
        max: 81,
      },
      {
        name: "Shield of the Divine +2",
        value: 300,
        exp: 100,
        min: 82,
        max: 84,
      },
      {
        name: "Spider Walk",
        value: 300,
        exp: 100,
        min: 85,
        max: 87,
      },
      {
        name: "Tongues",
        value: 500,
        exp: 300,
        min: 88,
        max: 90,
      },
      {
        name: "Water Breathing",
        value: 500,
        exp: 300,
        min: 91,
        max: 93,
      },
      {
        name: "Water Stride",
        value: 900,
        exp: 700,
        min: 94,
        max: 96,
      },
      {
        name: "Youth",
        value: 12000,
        exp: 1500,
        min: 97,
        max: 99,
      },
      {
        name: "Trap Entity",
        value: 1100,
        exp: 900,
        min: 100,
        max: 100,
      },
    ],
  },
  {
    percentile: "16-30%",
    name: "Scroll",
    min: 16,
    max: 30,
    options: [
      {
        name: "1 Spell Level",
        value: 300,
        exp: 100,
        min: 1,
        max: 8,
      },
      {
        name: "2 Spell Levels",
        value: 400,
        exp: 200,
        min: 9,
        max: 16,
      },
      {
        name: "3 Spell Levels",
        value: 500,
        exp: 300,
        min: 17,
        max: 24,
      },
      {
        name: "4 Spell Levels",
        value: 600,
        exp: 400,
        min: 25,
        max: 32,
      },
      {
        name: "5 Spell Levels",
        value: 700,
        exp: 500,
        min: 33,
        max: 40,
      },
      {
        name: "6 Spell Levels",
        value: 800,
        exp: 600,
        min: 41,
        max: 45,
      },
      {
        name: "7 Spell Levels",
        value: 900,
        exp: 700,
        min: 46,
        max: 50,
      },
      {
        name: "8 Spell Levels",
        value: 1000,
        exp: 800,
        min: 51,
        max: 55,
      },
      {
        name: "9 Spell Levels",
        value: 1100,
        exp: 900,
        min: 56,
        max: 60,
      },
      {
        name: "10 Spell Levels",
        value: 1200,
        exp: 1000,
        min: 61,
        max: 65,
      },
      {
        name: "11 Spell Levels",
        value: 1300,
        exp: 1100,
        min: 66,
        max: 68,
      },
      {
        name: "12 Spell Levels",
        value: 1400,
        exp: 1200,
        min: 69,
        max: 71,
      },
      {
        name: "13 Spell Levels",
        value: 1500,
        exp: 1300,
        min: 72,
        max: 74,
      },
      {
        name: "14 Spell Levels",
        value: 1700,
        exp: 1500,
        min: 75,
        max: 77,
      },
      {
        name: "15 Spell Levels",
        value: 1700,
        exp: 1500,
        min: 78,
        max: 80,
      },
      {
        name: "Teleport Accurately",
        value: 900,
        exp: 700,
        min: 81,
        max: 82,
      },
      {
        name: "Symbol",
        value: 1000,
        exp: 800,
        min: 83,
        max: 84,
      },
      {
        name: "Trap Entity",
        value: 1100,
        exp: 900,
        min: 85,
        max: 86,
      },
      {
        name: "Time Control",
        value: 1100,
        exp: 900,
        min: 87,
        max: 88,
      },
      {
        name: "Resurrection without Error",
        value: 1100,
        exp: 900,
        min: 89,
        max: 90,
      },
      {
        name: "Heal in Area",
        value: 1000,
        exp: 800,
        min: 91,
        max: 92,
      },
      {
        name: "Gate",
        value: 1100,
        exp: 900,
        min: 93,
        max: 94,
      },
      {
        name: "Create Extraordinary Undead",
        value: 1000,
        exp: 800,
        min: 95,
        max: 96,
      },
      {
        name: "Shapeshift",
        value: 1100,
        exp: 900,
        min: 97,
        max: 98,
      },
      {
        name: "Clone",
        value: 1100,
        exp: 900,
        min: 99,
        max: 100,
      },
    ],
  },
  {
    percentile: "31-45%",
    name: "Weapon",
    min: 31,
    max: 45,
    bonuses: [
      {
        type: "+1",
        min: 1,
        max: 45,
        value: 1000,
        exp: 250,
      },
      {
        type: "+2",
        min: 46,
        max: 75,
        value: 4000,
        exp: 750,
      },
      {
        type: "+3",
        min: 76,
        max: 90,
        value: 9000,
        exp: 1200,
      },
      {
        type: "+4",
        min: 91,
        max: 98,
        value: 16000,
        exp: 1750,
      },
      {
        type: "+5",
        min: 99,
        max: 100,
        value: 25000,
        exp: 2500,
      },
    ],
    options: [
      {
        name: "Sword",
        min: 1,
        max: 40,
        options: [
          {
            name: "Bastard Sword",
            min: 1,
            max: 10,
          },
          {
            options: ["Broad Sword", "Falchion"],
            min: 11,
            max: 30,
          },
          {
            name: ["Short Sword", "Scimitar", "Rapier"],
            min: 41,
            max: 50,
          },
          {
            name: "Long Sword",
            min: 51,
            max: 90,
          },
          {
            name: "Two Handed Sword",
            min: 91,
            max: 100,
          },
        ],
      },
      {
        name: "Spcial Sword",
        min: 41,
        max: 50,
        options: [
          {
            name: "Bane Sword",
            min: 1,
            max: 8,
            value: 13500,
            exp: 4500,
          },
          {
            name: "Sword of Dancing",
            min: 9,
            max: 16,
            value: 12500,
            exp: 4100,
          },
          {
            name: "Sword of Defending",
            min: 17,
            max: 24,
            value: 24500,
            exp: 8100,
          },
          {
            name: "Dragon Slayer",
            min: 25,
            max: 32,
            value: 29000,
            exp: 7250,
          },
          {
            name: "Featheredged Sword",
            min: 33,
            max: 36,
            value: 31750,
            exp: 15000,
          },
          {
            name: "Flaming Sword",
            min: 37,
            max: 44,
            value: 7750,
            exp: 2000,
          },
          {
            name: "Frostfire",
            min: 45,
            max: 52,
            value: 13725,
            exp: 3000,
          },
          {
            name: "Holy Avenger",
            min: 53,
            max: 56,
            value: 55000,
            exp: 27000,
          },
          {
            name: "Sword of Life Thieving",
            min: 57,
            max: 60,
            value: 17000,
            exp: 5600,
          },
          {
            name: "Luck Blade",
            min: 61,
            max: 68,
            value: 21500,
            exp: 7100,
          },
          {
            name: "Nine Lives Theif",
            min: 69,
            max: 72,
            value: 8500,
            exp: 2800,
          },
          {
            name: "Sword of Puncturing",
            min: 73,
            max: 80,
            value: 12000,
            exp: 3000,
          },
          {
            name: "Sword of Stinging",
            min: 81,
            max: 88,
            value: 16000,
            exp: 5300,
          },
          {
            name: "Sylvan Blade",
            min: 89,
            max: 92,
            value: 10000,
            exp: 3000,
          },
          {
            name: "Vorpal Sword",
            min: 93,
            max: 100,
            value: 38750,
            exp: 19000,
          },
        ],
      },
      {
        name: "Miscellaneous Weapon",
        min: 51,
        max: 90,
        options: [
          {
            name: "10 Arrows †",
            min: 1,
            max: 2,
          },
          {
            name: "Axe, battle",
            min: 3,
            max: 8,
          },
          {
            name: "Axe, hand/throwing",
            min: 9,
            max: 12,
          },
          {
            name: "Axe, two–handed",
            min: 13,
            max: 16,
          },
          {
            name: "Bardiche",
            min: 17,
            max: 20,
          },
          {
            name: "10 Bolts †",
            min: 21,
            max: 24,
          },
          {
            name: "Bow †",
            min: 25,
            max: 28,
          },
          {
            name: "Club",
            min: 29,
            max: 32,
          },
          {
            name: "Crossbow †",
            min: 33,
            max: 36,
          },
          {
            name: "Crowbill (Lucerne)",
            min: 37,
            max: 40,
          },
          {
            name: "Dagger",
            min: 41,
            max: 44,
          },
          {
            name: "Dart",
            min: 45,
            max: 48,
          },
          {
            name: "Flail †",
            min: 49,
            max: 52,
          },
          {
            name: "Halberd",
            min: 53,
            max: 56,
          },
          {
            name: "Hammer †",
            min: 57,
            max: 60,
          },
          {
            name: "Javelin",
            min: 61,
            max: 64,
          },
          {
            name: "Lance †",
            min: 65,
            max: 68,
          },
          {
            name: "Mace †",
            min: 69,
            max: 72,
          },
          {
            name: "Morningstar",
            min: 73,
            max: 76,
          },
          {
            name: "Polearm †",
            min: 77,
            max: 80,
          },
          {
            name: "Sling",
            min: 81,
            max: 84,
          },
          {
            name: "Spear †",
            min: 85,
            max: 88,
          },
          {
            name: "Staff",
            min: 89,
            max: 92,
          },
          {
            name: "Trident",
            min: 93,
            max: 96,
          },
          {
            name: "Whip",
            min: 97,
            max: 100,
          },
        ],
      },
      {
        name: "Special Weapon",
        min: 91,
        max: 100,
        options: [
          {
            name: "Bane Weapon",
            min: 1,
            max: 8,
            value: 13500,
            exp: 4500,
          },
          {
            name: "Dagger of Envenomation",
            min: 9,
            max: 16,
            value: 4750,
            exp: 1070,
          },
          {
            name: "Dwarven Hammer of Throwing",
            min: 17,
            max: 24,
            value: 18000,
            exp: 6000,
          },
          {
            name: "Featheredged Axe",
            min: 25,
            max: 28,
            value: 31750,
            exp: 15000,
          },
          {
            name: "Lightning Javelin",
            min: 29,
            max: 36,
            value: 4500,
            exp: 450,
          },
          {
            name: "Mace of Banishment",
            min: 37,
            max: 40,
            value: 17500,
            exp: 5800,
          },
          {
            name: "Mace of Scourge",
            min: 41,
            max: 48,
            value: 8500,
            exp: 2100,
          },
          {
            name: "Mace of Turning",
            min: 49,
            max: 56,
            value: 25500,
            exp: 8500,
          },
          {
            name: "Nine Lives Theif",
            min: 57,
            max: 60,
            value: 8500,
            exp: 2800,
          },
          {
            name: "Oathkeeper Bow",
            min: 61,
            max: 64,
            value: 25000,
            exp: 5000,
          },
          {
            name: "Slaying Arrow/Bolt",
            min: 65,
            max: 68,
            value: 9500,
            exp: 2300,
          },
          {
            name: "Sleep Arrow/Bolt",
            min: 69,
            max: 76,
            value: 1250,
            exp: 350,
          },
          {
            name: "Weapon of Stinging",
            min: 77,
            max: 84,
            value: 16000,
            exp: 5300,
          },
          {
            name: "Sylvan Weapon",
            min: 85,
            max: 92,
            value: 10000,
            exp: 3000,
          },
          {
            name: "Trident of Sea Creature Command",
            min: 93,
            max: 100,
            value: 5000,
            exp: 1200,
          },
        ],
      },
    ],
  },
  {
    percentile: "46-60%",
    name: "",
    min: 46,
    max: 60,
    bonuses: [
      {
        type: "+1",
        min: 1,
        max: 45,
        value: 1000,
        exp: 250,
      },
      {
        type: "+2",
        min: 46,
        max: 75,
        value: 4000,
        exp: 750,
      },
      {
        type: "+3",
        min: 76,
        max: 90,
        value: 9000,
        exp: 1200,
      },
      {
        type: "+4",
        min: 91,
        max: 98,
        value: 16000,
        exp: 1750,
      },
      {
        type: "+5",
        min: 99,
        max: 100,
        value: 25000,
        exp: 2500,
      },
    ],
    options: [
      {
        name: "Shield",
        min: 1,
        max: 75,
        options: [
          {
            name: "Buckler",
            min: 1,
            max: 40,
          },
          {
            name: "Medium Shield",
            min: 41,
            max: 70,
          },
          {
            name: "Large Shield",
            min: 71,
            max: 90,
          },
          {
            name: "Pavis",
            min: 91,
            max: 99,
          },
          {
            name: "Random Shield",
            min: 100,
            max: 100,
            options: [
              {
                name: "Animated Shield",
                min: 1,
                max: 40,
              },
              {
                name: "Shield of Bashing",
                min: 41,
                max: 70,
              },
              {
                name: "Blinding Shield",
                min: 71,
                max: 90,
              },
              {
                name: "Shield of the Roaring Lion",
                min: 91,
                max: 100,
              },
            ],
          },
        ],
      },
      {
        name: "Armor",
        min: 76,
        max: 100,
        options: [
          {
            name: "Padded Armor",
            min: 1,
            max: 13,
          },
          {
            name: "Leather Armor",
            min: 14,
            max: 29,
          },
          {
            name: "Studded Armor",
            min: 30,
            max: 36,
          },
          {
            name: "Ring Armor",
            min: 37,
            max: 46,
          },
          {
            name: "Mail Shirt",
            min: 47,
            max: 51,
          },
          {
            name: "Hide Armor",
            min: 52,
            max: 61,
          },
          {
            name: "Scale Mail",
            min: 62,
            max: 71,
          },
          {
            name: "Chainmail",
            min: 72,
            max: 76,
          },
          {
            name: "Breastplate",
            min: 77,
            max: 85,
          },
          {
            name: "Splint Mail",
            min: 86,
            max: 90,
          },
          {
            name: "Banded Mail",
            min: 91,
            max: 95,
          },
          {
            name: "Plate Mail",
            min: 96,
            max: 98,
          },
          {
            name: "Full Plate",
            min: 99,
            max: 99,
          },
          {
            name: "Random Armor",
            min: 100,
            max: 100,
            options: [
              {
                name: "Cold/Fire Resistance Armor",
                min: 1,
                max: 18,
              },
              {
                name: "Dwarven Fullplate",
                min: 19,
                max: 36,
              },
              {
                name: "Elven Chainmail",
                min: 37,
                max: 54,
              },
              {
                name: "Armor of the Ethereal Knight",
                min: 55,
                max: 64,
              },
              {
                name: "Plate Armor of the Diver",
                min: 65,
                max: 82,
              },
              {
                name: "Spell Resistance Armor",
                min: 83,
                max: 100,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    percentile: "61-80%",
    name: "",
    min: 61,
    max: 80,
    options: [
      {
        min: 1,
        max: 20,
        options: [
          {
            name: "Amulet of Bestial Armor",
            min: 1,
            max: 4,
            value: "1,000–25,000",
            exp: "500xp per bonus",
          },
          {
            name: "Amulet of Mighty Blows",
            min: 5,
            max: 8,
            value: "1,000–25,000",
            exp: "500xp per bonus",
          },
          {
            name: "Amulet of Planar Travel",
            min: 9,
            max: 12,
            value: 20250,
            exp: 6750,
          },
          {
            name: "Amulet of Superior Health",
            min: 13,
            max: 16,
            value: "4,000–36,000",
            exp: "500xp per bonus",
          },
          {
            name: "Bag of Beasts",
            min: 17,
            max: 20,
            value: "1,000/4,000/16,000",
            exp: "300/1,250/3,000xp",
          },
          {
            name: "Belt of the Giant",
            min: 21,
            max: 24,
            value: "10,000–60,000",
            exp: 1000,
          },
          {
            name: "Boat, Foldable",
            min: 25,
            max: 28,
            value: 17500,
            exp: 1750,
          },
          {
            name: "Book of the Budget-Conscious Spells",
            min: 29,
            max: 32,
            value: 112000,
            exp: 11200,
          },
          {
            name: "Boots of the Elves",
            min: 33,
            max: 36,
            value: 13500,
            exp: 3500,
          },
          {
            name: "Boots of the Flight of Foot",
            min: 37,
            max: 40,
            value: 12750,
            exp: 1275,
          },
          {
            name: "Boots of Levitation",
            min: 41,
            max: 44,
            value: 11000,
            exp: 2500,
          },
          {
            name: "Boots of Striding and Leaping",
            min: 45,
            max: 48,
            value: 9000,
            exp: 900,
          },
          {
            name: "Boots of Teleporting",
            min: 49,
            max: 52,
            value: 20250,
            exp: 6750,
          },
          {
            name: "Boots of the Winter",
            min: 53,
            max: 56,
            value: 9500,
            exp: 950,
          },
          {
            name: "Boots of Water Elemental Command",
            min: 57,
            max: 60,
            value: 25500,
            exp: 8500,
          },
          {
            name: "Bracers of Armor",
            min: 61,
            max: 64,
            value: "1,000–25,000",
            exp: "500xp per bonus",
          },
          {
            name: "Bracers of Deflection",
            min: 65,
            max: 68,
            value: 13500,
            exp: 4500,
          },
          {
            name: "Brazier of Elemental Fire Command",
            min: 69,
            max: 72,
            value: 25000,
            exp: 8500,
          },
          {
            name: "Brooch of Shielding",
            min: 73,
            max: 76,
            value: 11500,
            exp: 1150,
          },
          {
            name: "Broomstick, Flying",
            min: 77,
            max: 80,
            value: 12750,
            exp: 4250,
          },
          {
            name: "Candle, Priest's",
            min: 81,
            max: 84,
            value: 22000,
            exp: 7300,
          },
          {
            name: "Cape, Trickster's",
            min: 85,
            max: 88,
            value: 16000,
            exp: 1600,
          },
          {
            name: "Carpet, Flying",
            min: 89,
            max: 92,
            value: 17250,
            exp: 5750,
          },
          {
            name: "Censer of Elemental Air Control",
            min: 93,
            max: 96,
            value: 25000,
            exp: 8500,
          },
          {
            name: "Cerements of Disintegration",
            min: 97,
            max: 100,
            value: 1650,
            exp: 165,
          },
        ],
      },
      {
        min: 21,
        max: 40,
        options: [
          {
            name: "Chime of Discordance",
            min: 1,
            max: 4,
            value: 13500,
            exp: 1350,
          },
          {
            name: "Chime, Opening",
            min: 5,
            max: 8,
            value: 10500,
            exp: 1050,
          },
          {
            name: "Circlet of Charisma",
            min: 9,
            max: 12,
            value: 11250,
            exp: 1125,
          },
          {
            name: "Cloak of the Bat",
            min: 13,
            max: 16,
            value: 13500,
            exp: 3000,
          },
          {
            name: "Cloak of Charisma",
            min: 17,
            max: 20,
            value: "4,000–25,000",
            exp: "500xp per bonus",
          },
          {
            name: "Cloak of Distortion",
            min: 21,
            max: 24,
            value: 17000,
            exp: 1700,
          },
          {
            name: "Cloak of the Elves",
            min: 25,
            max: 28,
            value: 15500,
            exp: 3000,
          },
          {
            name: "Cloak of Ethereal Travel",
            min: 29,
            max: 32,
            value: 11250,
            exp: 2500,
          },
          {
            name: "Cloak of the Ray",
            min: 33,
            max: 36,
            value: 11250,
            exp: 2500,
          },
          {
            name: "Cloak of Resistance",
            min: 37,
            max: 40,
            value: "1,000–25,000",
            exp: "500xp per bonus",
          },
          {
            name: "Cloak of the Spider",
            min: 41,
            max: 44,
            value: 17500,
            exp: 1750,
          },
          {
            name: "Crystal Ball",
            min: 45,
            max: 48,
            value: "see text for ",
            exp: 5000,
          },
          {
            name: "Cube of Alarm",
            min: 49,
            max: 52,
            value: 1400,
            exp: 140,
          },
          {
            name: "Cube, Carnelian",
            min: 53,
            max: 56,
            value: 24750,
            exp: 4500,
          },
          {
            name: "Cube of Cold Resistance",
            min: 57,
            max: 60,
            value: 12750,
            exp: 1270,
          },
          {
            name: "Cube of Force",
            min: 61,
            max: 64,
            value: 47250,
            exp: 4000,
          },
          {
            name: "Decanter of Unending Water",
            min: 65,
            max: 68,
            value: 13500,
            exp: 1350,
          },
          {
            name: "Dimensional Pouch",
            min: 69,
            max: 72,
            value: 25500,
            exp: 8500,
          },
          {
            name: "Dimensional Backpack",
            min: 73,
            max: 76,
            value: 12250,
            exp: 1225,
          },
          {
            name: "Drums of Doom",
            min: 77,
            max: 80,
            value: 4750,
            exp: 475,
          },
          {
            name: "Dust of Appearing",
            min: 81,
            max: 84,
            value: 8500,
            exp: 850,
          },
          {
            name: "Dust of Seeming",
            min: 85,
            max: 88,
            value: 5500,
            exp: 550,
          },
          {
            name: "Dust of Vanishing",
            min: 89,
            max: 92,
            value: 5500,
            exp: 550,
          },
          {
            name: "Eagle Eyes",
            min: 93,
            max: 96,
            value: 4250,
            exp: 425,
          },
          {
            name: "Efficient Quiver",
            min: 97,
            max: 100,
            value: 8550,
            exp: 850,
          },
        ],
      },
      {
        min: 41,
        max: 60,
        options: [
          {
            name: "Eversmoking Lamp",
            min: 1,
            max: 4,
            value: 4250,
            exp: 425,
          },
          {
            name: "Feathers of Power",
            min: 5,
            max: 8,
            value: 4500,
            exp: 450,
          },
          {
            name: "Figurines of Animal Awakening",
            min: 9,
            max: 12,
            value: "see text for ",
            exp: "see text for xp",
          },
          {
            name: "Gauntlets of Ogrish Might",
            min: 13,
            max: 16,
            value: 9500,
            exp: 950,
          },
          {
            name: "Gem of Elemental Summoning",
            min: 17,
            max: 20,
            value: 20250,
            exp: 2000,
          },
          {
            name: "Gem of Light",
            min: 21,
            max: 24,
            value: 17750,
            exp: 2000,
          },
          {
            name: "Gem of Truth",
            min: 25,
            max: 28,
            value: 15250,
            exp: 1500,
          },
          {
            name: "Gloves of Dexterity",
            min: 29,
            max: 32,
            value: "1,000–25,000",
            exp: "500xp per bonus,",
          },
          {
            name: "Gloves of the Wildman",
            min: 33,
            max: 36,
            value: 9000,
            exp: 900,
          },
          {
            name: "Greatstone",
            min: 37,
            max: 40,
            value: 2000,
            exp: 1000,
          },
          {
            name: "Harp of Ensourcellment",
            min: 41,
            max: 44,
            value: 7750,
            exp: 2000,
          },
          {
            name: "Hat of False Appearance",
            min: 45,
            max: 48,
            value: 5500,
            exp: 550,
          },
          {
            name: "Helm of Comprehension",
            min: 49,
            max: 52,
            value: 4250,
            exp: 425,
          },
          {
            name: "Helm of the Diver",
            min: 53,
            max: 56,
            value: 4500,
            exp: 1125,
          },
          {
            name: "Helm of the Glimmering",
            min: 57,
            max: 60,
            value: 34750,
            exp: 3000,
          },
          {
            name: "Helm of the Mind Reader",
            min: 61,
            max: 64,
            value: 17250,
            exp: 3450,
          },
          {
            name: "Helm of Teleporting",
            min: 65,
            max: 68,
            value: 20250,
            exp: 2250,
          },
          {
            name: "Horn of the Merfolk",
            min: 69,
            max: 72,
            value: 12500,
            exp: 2500,
          },
          {
            name: "Horn of Mist",
            min: 73,
            max: 76,
            value: 4250,
            exp: 1050,
          },
          {
            name: "Horn of Valhalla",
            min: 77,
            max: 80,
            value: 32000,
            exp: "1,250xp (Doubles with each horn)",
          },
          {
            name: "Horseshoes of Swiftness",
            min: 81,
            max: 84,
            value: 7750,
            exp: 775,
          },
          {
            name: "Horseshoes of the Windrunner",
            min: 85,
            max: 88,
            value: 9750,
            exp: 975,
          },
          {
            name: "Instant Fortress",
            min: 89,
            max: 92,
            value: 22500,
            exp: 2250,
          },
          {
            name: "Ioun Stones",
            min: 93,
            max: 96,
            value: "See text for",
            exp: "See text for xp",
          },
          {
            name: "Iron Bands of Binding",
            min: 97,
            max: 100,
            value: 17500,
            exp: 1750,
          },
        ],
      },
      {
        min: 61,
        max: 80,
        options: [
          {
            name: "Iron Phial",
            min: 1,
            max: 4,
            value: 0,
            exp: 0,
          },
          {
            name: "Jewel of Healing",
            min: 5,
            max: 8,
            value: 17000,
            exp: 1000,
          },
          {
            name: "Jewel of Health",
            min: 9,
            max: 12,
            value: 9500,
            exp: 950,
          },
          {
            name: "Jewel of Proof Against Poison",
            min: 13,
            max: 16,
            value: 9500,
            exp: 950,
          },
          {
            name: "Jewel of Wisdom",
            min: 17,
            max: 20,
            value: "1,000–25,000",
            exp: "500xp per bonus",
          },
          {
            name: "Lyre of Creation",
            min: 21,
            max: 24,
            value: 13500,
            exp: 2000,
          },
          {
            name: "Magic Lamp",
            min: 25,
            max: 28,
            value: 0,
            exp: 0,
          },
          {
            name: "Mantle of Superior Spell Resistance",
            min: 29,
            max: 32,
            value: 200000,
            exp: 20000,
          },
          {
            name: "Manual of Bodily Wellness",
            min: 33,
            max: 36,
            value: "10,000–60,000",
            exp: "500xp per bonus",
          },
          {
            name: "Manual of Dexterous Action",
            min: 37,
            max: 40,
            value: "10,000–60,000",
            exp: "500xp per bonus",
          },
          {
            name: "Manual of Gainful Strength",
            min: 41,
            max: 44,
            value: "10,000–60,000",
            exp: "500xp per bonus",
          },
          {
            name: "Mattock of the Ancient Ones",
            min: 45,
            max: 48,
            value: 11500,
            exp: 1150,
          },
          {
            name: "Maul of the Ancient Ones",
            min: 49,
            max: 52,
            value: 13500,
            exp: 1350,
          },
          {
            name: "Medallion of ESP",
            min: 53,
            max: 56,
            value: 5500,
            exp: 1500,
          },
          {
            name: "Mirror of Dark Reflection",
            min: 57,
            max: 60,
            value: 25600,
            exp: 2560,
          },
          {
            name: "Mirror of Revealing",
            min: 61,
            max: 64,
            value: 37250,
            exp: 3720,
          },
          {
            name: "Mirror of Soul Trapping",
            min: 65,
            max: 68,
            value: 39000,
            exp: 2300,
          },
          {
            name: "Necklace of Fiery Beads",
            min: 69,
            max: 72,
            value: "See text for",
            exp: "See text for xp",
          },
          {
            name: "Necklace of Fresh Air",
            min: 73,
            max: 76,
            value: 4500,
            exp: 450,
          },
          {
            name: "Orb of Atmospheric Control",
            min: 77,
            max: 80,
            value: 49500,
            exp: 2500,
          },
          {
            name: "Pearl of Recall",
            min: 81,
            max: 84,
            value: "1,000–81,000",
            exp: "1000 per level of spell",
          },
          {
            name: "Pearl of the Sea Kings",
            min: 85,
            max: 88,
            value: 13500,
            exp: 1350,
          },
          {
            name: "Phylactery of the Devout",
            min: 89,
            max: 92,
            value: 5500,
            exp: 1250,
          },
          {
            name: "Phylactery of Turning",
            min: 93,
            max: 96,
            value: 16000,
            exp: 1600,
          },
          {
            name: "Piper's Pipes",
            min: 97,
            max: 100,
            value: 7500,
            exp: 750,
          },
        ],
      },
      {
        min: 81,
        max: 100,
        options: [
          {
            name: "Portable Hole",
            min: 1,
            max: 4,
            value: 29250,
            exp: 2950,
          },
          {
            name: "Portable Portal",
            min: 5,
            max: 8,
            value: 40450,
            exp: 2000,
          },
          {
            name: "Restorative Salve",
            min: 9,
            max: 12,
            value: 5500,
            exp: 550,
          },
          {
            name: "Robe of the Camouflage",
            min: 13,
            max: 16,
            value: 23000,
            exp: 2300,
          },
          {
            name: "Robe of the High Magus",
            min: 17,
            max: 20,
            value: 75000,
            exp: 7500,
          },
          {
            name: "Robe of Many Colors",
            min: 21,
            max: 24,
            value: 13500,
            exp: 1350,
          },
          {
            name: "Robe of Many Items",
            min: 25,
            max: 28,
            value: 14000,
            exp: 1400,
          },
          {
            name: "Robe of Oculus",
            min: 29,
            max: 32,
            value: 17500,
            exp: 1750,
          },
          {
            name: "Rogue's Rope",
            min: 33,
            max: 36,
            value: 5750,
            exp: 575,
          },
          {
            name: "Rope of Entanglement",
            min: 37,
            max: 40,
            value: 7750,
            exp: 775,
          },
          {
            name: "Scabbard of Keen Edges",
            min: 41,
            max: 44,
            value: 17500,
            exp: 1700,
          },
          {
            name: "Scarab of Protection",
            min: 45,
            max: 48,
            value: 34000,
            exp: 1200,
          },
          {
            name: "Slippers of Spider Walking",
            min: 49,
            max: 52,
            value: 9000,
            exp: 900,
          },
          {
            name: "Stone of Elemental Earth Command",
            min: 53,
            max: 56,
            value: "10,000–60,000",
            exp: 8500,
          },
          {
            name: "Stone of Fortune",
            min: 57,
            max: 60,
            value: 4250,
            exp: 425,
          },
          {
            name: "Stone Horse",
            min: 61,
            max: 64,
            value: 8500,
            exp: 850,
          },
          {
            name: "String of Prayer Beads",
            min: 65,
            max: 68,
            value: "See text for ",
            exp: "See text for xp",
          },
          {
            name: "Tome of Magnetic Charisma",
            min: 69,
            max: 72,
            value: "1,000–25,000",
            exp: "500 per bonus",
          },
          {
            name: "Tome of Sagacious Wisdom",
            min: 73,
            max: 76,
            value: "1,000–25,000",
            exp: "500 per bonus",
          },
          {
            name: "Tome of Superior Intellect",
            min: 77,
            max: 80,
            value: "1,000–25,000",
            exp: "500xp per bonus",
          },
          {
            name: "Transporter Gates",
            min: 81,
            max: 84,
            value: "30,500 - if found together",
            exp: "500 per bonus",
          },
          {
            name: "Trumpet of Blasting",
            min: 85,
            max: 88,
            value: 17500,
            exp: 1750,
          },
          {
            name: "Trumpet of Good and Evil",
            min: 89,
            max: 92,
            value: 4250,
            exp: 1050,
          },
          {
            name: "Wind-Master's Fan",
            min: 93,
            max: 96,
            value: 5500,
            exp: 550,
          },
          {
            name: "Wings of Flight",
            min: 97,
            max: 100,
            value: 15750,
            exp: 1575,
          },
        ],
      },
    ],
  },
  {
    percentile: "81-90%",
    name: "",
    min: 81,
    max: 90,
    options: [
      {
        name: "Blinking Band",
        min: 1,
        max: 4,
        value: 9800,
        exp: 1960,
      },
      {
        name: "Ring of Animal Loyalty",
        min: 5,
        max: 8,
        value: 1650,
        exp: 330,
      },
      {
        name: "Ring of Armor",
        min: 9,
        max: 12,
        value: "2,300/5,300/11,300/17,300/26,300/37,300",
        exp: "xp value is 20% of gold piece value",
      },
      {
        name: "Ring of the Climber",
        min: 13,
        max: 16,
        value: 2800,
        exp: 560,
      },
      {
        name: "Ring of Disguise",
        min: 17,
        max: 20,
        value: 5800,
        exp: 1160,
      },
      {
        name: "Ring of the Djinni Master",
        min: 21,
        max: 21,
        value: 114750,
        exp: 5000,
      },
      {
        name: "Ring of Dodging",
        min: 22,
        max: 25,
        value: 20000,
        exp: 5000,
      },
      {
        name: "Ring of Eldritch Wizardry",
        min: 26,
        max: 29,
        value: "20,000/40,000/70,000/100,000",
        exp: "xp value is 1,000 per level of spell",
      },
      {
        name: "Ring of Elemental Command [One of the Four]",
        min: 30,
        max: 30,
        value: 1550,
        exp: 310,
      },
      {
        name: "Ring of Feather-Lightness",
        min: 31,
        max: 34,
        value: 1550,
        exp: 310,
      },
      {
        name: "Ring of Free Motion",
        min: 35,
        max: 38,
        value: 8300,
        exp: 1660,
      },
      {
        name: "Ring of Friend Shielding",
        min: 39,
        max: 41,
        value: 6050,
        exp: 1210,
      },
      {
        name: "Ring of Granting",
        min: 42,
        max: 42,
        value: 114750,
        exp: 5000,
      },
      {
        name: "Ring of Invisibility",
        min: 43,
        max: 44,
        value: 5800,
        exp: 1160,
      },
      {
        name: "Ring of Mighty Leaping",
        min: 45,
        max: 48,
        value: 1550,
        exp: 310,
      },
      {
        name: "Ring of Nourishment",
        min: 49,
        max: 51,
        value: 2800,
        exp: 560,
      },
      {
        name: "Ring of Opaque Thought",
        min: 52,
        max: 54,
        value: 5800,
        exp: 1160,
      },
      {
        name: "Ring of Ramming",
        min: 55,
        max: 58,
        value: 5800,
        exp: 1160,
      },
      {
        name: "Ring of Regeneration",
        min: 59,
        max: 59,
        value: 24050,
        exp: 4810,
      },
      {
        name: "Ring of Resistance",
        min: 60,
        max: 63,
        value: 25000,
        exp: 5000,
      },
      {
        name: "Ring of Spectral Shielding",
        min: 64,
        max: 67,
        value: 5050,
        exp: 1010,
      },
      {
        name: "Ring of Spell Deflection",
        min: 68,
        max: 71,
        value: 41800,
        exp: 8360,
      },
      {
        name: "Ring of Spell Keeping",
        min: 72,
        max: 75,
        value: "5,050/12,550/38,000",
        exp: "xp value is 20% of gold piece value",
      },
      {
        name: "Ring of Spell Negation",
        min: 76,
        max: 80,
        value: 5050,
        exp: 1010,
      },
      {
        name: "Ring of Starlight",
        min: 81,
        max: 84,
        value: 9300,
        exp: 1860,
      },
      {
        name: "Ring of Swimming",
        min: 85,
        max: 88,
        value: 1300,
        exp: 260,
      },
      {
        name: "Ring of Telekinetic Power",
        min: 89,
        max: 92,
        value: 12550,
        exp: 2510,
      },
      {
        name: "Ring of Water Striding",
        min: 93,
        max: 96,
        value: 5800,
        exp: 1160,
      },
      {
        name: "Ring of X–Ray Vision",
        min: 97,
        max: 100,
        value: 9300,
        exp: 930,
      },
    ],
  },
  {
    percentile: "91-97%",
    name: "",
    min: 91,
    max: 97,
    options: [
      {
        name: "Rod of Atrophy",
        min: 1,
        max: 3,
        value: 25000,
        exp: 4000,
      },
      {
        name: "Rod of Chaos",
        min: 4,
        max: 6,
        value: 13500,
        exp: 2250,
      },
      {
        name: "Rod of Deactivation",
        min: 7,
        max: 10,
        value: 9500,
        exp: 1500,
      },
      {
        name: "Rod of Disenchantment",
        min: 11,
        max: 14,
        value: 13500,
        exp: 2250,
      },
      {
        name: "Rod of Regality",
        min: 15,
        max: 17,
        value: 20000,
        exp: 3200,
      },
      {
        name: "Rod of the Serpent",
        min: 18,
        max: 21,
        value: 8750,
        exp: 1400,
      },
      {
        name: "Rod of Spell Stealing",
        min: 22,
        max: 24,
        value: 50000,
        exp: 8300,
      },
      {
        name: "Rod of Supreme Usefulness",
        min: 25,
        max: 27,
        value: 20500,
        exp: 3400,
      },
      {
        name: "Rod of Thunderstorms",
        min: 28,
        max: 30,
        value: 29000,
        exp: 4800,
      },
      {
        name: "Staff of Abjuration",
        min: 31,
        max: 33,
        value: 54000,
        exp: 9000,
      },
      {
        name: "Staff of Conjuration",
        min: 34,
        max: 36,
        value: 47000,
        exp: 7800,
      },
      {
        name: "Staff of Cryomancy",
        min: 37,
        max: 40,
        value: 32500,
        exp: 5400,
      },
      {
        name: "Staff of the Druids",
        min: 41,
        max: 43,
        value: 42000,
        exp: 7000,
      },
      {
        name: "Staff of Evocation",
        min: 43,
        max: 46,
        value: 47000,
        exp: 7800,
      },
      {
        name: "Staff of Healing",
        min: 47,
        max: 50,
        value: 31000,
        exp: 5100,
      },
      {
        name: "Staff of Power",
        min: 51,
        max: 53,
        value: 72000,
        exp: 12000,
      },
      {
        name: "Staff of Pyromancy",
        min: 54,
        max: 57,
        value: 23000,
        exp: 3800,
      },
      {
        name: "Staff of Resurrection",
        min: 58,
        max: 60,
        value: 41000,
        exp: 6800,
      },
      {
        name: "Wand - 1st Level",
        min: 61,
        max: 70,
        value: 750,
        exp: 500,
      },
      {
        name: "Wand - 2nd Level",
        min: 71,
        max: 75,
        value: 2250,
        exp: 1000,
      },
      {
        name: "Wand - 3rd Level",
        min: 76,
        max: 80,
        value: 4500,
        exp: 1500,
      },
      {
        name: "Wand - 4th Level",
        min: 81,
        max: 83,
        value: 7500,
        exp: 2000,
      },
      {
        name: "Wand - 5th Level",
        min: 84,
        max: 85,
        value: 12000,
        exp: 3000,
      },
      {
        name: "Wand - 6th Level",
        min: 86,
        max: 87,
        value: 16500,
        exp: 4000,
      },
      {
        name: "Wand - 7th Level",
        min: 88,
        max: 89,
        value: 21750,
        exp: 5000,
      },
      {
        name: "Wand - 8th Level",
        min: 90,
        max: 90,
        value: 27750,
        exp: 6000,
      },
      {
        name: "Wand - 9th Level",
        min: 91,
        max: 91,
        value: 34500,
        exp: 7000,
      },
      {
        name: "Wand of Colors",
        min: 92,
        max: 92,
        value: 12250,
        exp: 2000,
      },
      {
        name: "Wand of Darkness",
        min: 93,
        max: 93,
        value: 12250,
        exp: 2000,
      },
      {
        name: "Wand of Dispel Magic",
        min: 94,
        max: 94,
        value: 16750,
        exp: 2800,
      },
      {
        name: "Wand of Invisibility",
        min: 95,
        max: 95,
        value: 31000,
        exp: 5000,
      },
      {
        name: "Wand of Levitate",
        min: 96,
        max: 96,
        value: 26000,
        exp: 4300,
      },
      {
        name: "Wand of Magi's Missile",
        min: 97,
        max: 97,
        value: 12250,
        exp: 2000,
      },
      {
        name: "Wand of Polymorph",
        min: 98,
        max: 98,
        value: 23000,
        exp: 3800,
      },
      {
        name: "Wand of Restoration",
        min: 99,
        max: 99,
        value: 18000,
        exp: 3000,
      },
      {
        name: "Wand of Suggestion",
        min: 100,
        max: 100,
        value: 14500,
        exp: 2400,
      },
    ],
  },
  {
    percentile: "98-99%",
    name: "Cursed Item",
    min: 98,
    max: 99,
    options: [
      {
        name: "Amulet of Inescapable Location",
        min: 1,
        max: 4,
      },
      {
        name: "Armor of Hate",
        min: 5,
        max: 8,
      },
      {
        name: "Bag of Uncontrollable Dance",
        min: 9,
        max: 12,
      },
      {
        name: "Bottle of Doom",
        min: 13,
        max: 16,
      },
      {
        name: "Bracers of Vulnerability",
        min: 17,
        max: 20,
      },
      {
        name: "Devouring Dimensional Pouch",
        min: 21,
        max: 24,
      },
      {
        name: "Gauntlets of Clumsiness",
        min: 25,
        max: 28,
      },
      {
        name: "Helm of Opposite Disposition",
        min: 29,
        max: 32,
      },
      {
        name: "Incense of Magical Obsession",
        min: 33,
        max: 36,
      },
      {
        name: "Jewel of Foul Rotting",
        min: 37,
        max: 40,
      },
      {
        name: "Mace of Gore",
        min: 41,
        max: 44,
      },
      {
        name: "Medallion of the Open Mind",
        min: 45,
        max: 48,
      },
      {
        name: "Necklace of Asphyxiation",
        min: 49,
        max: 52,
      },
      {
        name: "Net of Return",
        min: 53,
        max: 56,
      },
      {
        name: "Potion of Poison",
        min: 57,
        max: 60,
      },
      {
        name: "Ring of Fumbling",
        min: 61,
        max: 64,
      },
      {
        name: "Robe of Enfeeblement",
        min: 65,
        max: 68,
      },
      {
        name: "Robe of Insects",
        min: 69,
        max: 72,
      },
      {
        name: "Scarab of Burrowing",
        min: 73,
        max: 76,
      },
      {
        name: "Spear, Backbiting",
        min: 77,
        max: 80,
      },
      {
        name: "Stone of Burden",
        min: 81,
        max: 84,
      },
      {
        name: "Sword, Berserking",
        min: 85,
        max: 88,
      },
      {
        name: "Sword, Vursed",
        min: 89,
        max: 92,
      },
      {
        name: "Vacuous Tome",
        min: 93,
        max: 96,
      },
      {
        name: "Zane’s Ire",
        min: 97,
        max: 100,
      },
    ],
  },
  {
    percentile: "98-99%",
    name: "Artifact",
    min: 100,
    max: 100,
    options: [
      {
        name: "Cowl of the Black Fox",
        min: 1,
        max: 4,
      },
      {
        name: "Deck of Wonder",
        min: 5,
        max: 8,
      },
      {
        name: "Diamond of Agony",
        min: 9,
        max: 10,
      },
      {
        name: "Ever-Compliant Rod",
        min: 11,
        max: 14,
      },
      {
        name: "Excalibur",
        min: 15,
        max: 16,
      },
      {
        name: "Hammer of Thunderbolts",
        min: 17,
        max: 20,
      },
      {
        name: "The Hand Which Knocks",
        min: 21,
        max: 24,
      },
      {
        name: "Infinite Spellbook",
        min: 25,
        max: 28,
      },
      {
        name: "Lantern of Revelation",
        min: 29,
        max: 32,
      },
      {
        name: "Limitless Sword",
        min: 33,
        max: 36,
      },
      {
        name: "Mace of the Dove",
        min: 37,
        max: 40,
      },
      {
        name: "Mantle of the Blessed Monk",
        min: 41,
        max: 44,
      },
      {
        name: "The Mighty Demon-Slayer",
        min: 45,
        max: 48,
      },
      {
        name: "The Orbs of the Dragon Masters",
        min: 49,
        max: 52,
      },
      {
        name: "Philosopher's Stone",
        min: 53,
        max: 56,
      },
      {
        name: "The Ring of Endless Wealth",
        min: 57,
        max: 60,
      },
      {
        name: "Scepter of the Gods",
        min: 61,
        max: 64,
      },
      {
        name: "Shield of Solar Incandescence",
        min: 65,
        max: 68,
      },
      {
        name: "Sphere of Obliteration",
        min: 69,
        max: 72,
      },
      {
        name: "Staff of the Magus",
        min: 73,
        max: 76,
      },
      {
        name: "The Staff of Penumbra",
        min: 77,
        max: 80,
      },
      {
        name: "Talisman of Obliteration",
        min: 81,
        max: 84,
      },
      {
        name: "Talisman of Unwavering Good",
        min: 85,
        max: 88,
      },
      {
        name: "Talisman of Unyielding Evil",
        min: 89,
        max: 92,
      },
      {
        name: "Tome of the Unclean",
        min: 93,
        max: 96,
      },
      {
        name: "Unerring Bow",
        min: 97,
        max: 100,
      }
    ],
  },
];
